"""phase3 npm write automation

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 15:40:17.064236
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npm_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=True),
    sa.Column('npm_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=320), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('probe_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('probe_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('nginx_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("action IN ('protect','unprotect')", name=op.f('ck_npm_changes_action_valid')),
    sa.CheckConstraint("status IN ('running','applied','rolled_back','rollback_failed','refused','interrupted')", name=op.f('ck_npm_changes_status_valid')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_npm_changes_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connection_id'], ['npm_connections.id'], name=op.f('fk_npm_changes_connection_id_npm_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['npm_hosts.id'], name=op.f('fk_npm_changes_host_id_npm_hosts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_npm_changes_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_npm_changes'))
    )
    op.create_index(op.f('ix_npm_changes_connection_id'), 'npm_changes', ['connection_id'], unique=False)
    op.create_index(op.f('ix_npm_changes_host_id'), 'npm_changes', ['host_id'], unique=False)
    op.create_index(op.f('ix_npm_changes_organization_id'), 'npm_changes', ['organization_id'], unique=False)
    op.create_index('uq_npm_changes_running_host', 'npm_changes', ['connection_id', 'npm_id'], unique=True, postgresql_where=sa.text("status = 'running'"))
    op.add_column('npm_connections', sa.Column('write_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('npm_connections', sa.Column('authentik_outpost_url', sa.String(length=2048), nullable=True))
    op.add_column('npm_connections', sa.Column('probe_host', sa.String(length=255), nullable=True))
    op.add_column('npm_connections', sa.Column('probe_http_port', sa.Integer(), server_default='80', nullable=False))
    op.add_column('npm_connections', sa.Column('probe_https_port', sa.Integer(), server_default='443', nullable=False))
    op.add_column('npm_hosts', sa.Column('vaultx_managed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npm_hosts', 'vaultx_managed')
    op.drop_column('npm_connections', 'probe_https_port')
    op.drop_column('npm_connections', 'probe_http_port')
    op.drop_column('npm_connections', 'probe_host')
    op.drop_column('npm_connections', 'authentik_outpost_url')
    op.drop_column('npm_connections', 'write_enabled')
    op.drop_index('uq_npm_changes_running_host', table_name='npm_changes', postgresql_where=sa.text("status = 'running'"))
    op.drop_index(op.f('ix_npm_changes_organization_id'), table_name='npm_changes')
    op.drop_index(op.f('ix_npm_changes_host_id'), table_name='npm_changes')
    op.drop_index(op.f('ix_npm_changes_connection_id'), table_name='npm_changes')
    op.drop_table('npm_changes')
    # ### end Alembic commands ###
