"""phase1 npm connector and catalog

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 13:10:39.453276
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('app_type', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auth_method', sa.String(length=32), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auth_method IN ('forward_auth','oidc','saml','header','access_list','app','none','unknown')", name=op.f('ck_applications_auth_method_valid')),
    sa.CheckConstraint("source IN ('npm','manual')", name=op.f('ck_applications_source_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_applications_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index(op.f('ix_applications_organization_id'), 'applications', ['organization_id'], unique=False)
    op.create_table('npm_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('identity', sa.String(length=320), nullable=False),
    sa.Column('secret_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('npm_version', sa.String(length=32), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=16), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("last_sync_status IS NULL OR last_sync_status IN ('ok','error')", name=op.f('ck_npm_connections_sync_status_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_npm_connections_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_npm_connections')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_npm_connections_organization_name')
    )
    op.create_index(op.f('ix_npm_connections_organization_id'), 'npm_connections', ['organization_id'], unique=False)
    op.create_table('npm_hosts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('npm_id', sa.Integer(), nullable=False),
    sa.Column('domain_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forward_scheme', sa.String(length=8), nullable=False),
    sa.Column('forward_host', sa.String(length=255), nullable=False),
    sa.Column('forward_port', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('nginx_online', sa.Boolean(), nullable=False),
    sa.Column('ssl', sa.Boolean(), nullable=False),
    sa.Column('ssl_forced', sa.Boolean(), nullable=False),
    sa.Column('access_list', sa.String(length=255), nullable=True),
    sa.Column('forward_auth', sa.Boolean(), nullable=False),
    sa.Column('detected_app_type', sa.String(length=64), nullable=True),
    sa.Column('detected_auth', sa.String(length=32), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_npm_hosts_application_id_applications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connection_id'], ['npm_connections.id'], name=op.f('fk_npm_hosts_connection_id_npm_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_npm_hosts_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_npm_hosts')),
    sa.UniqueConstraint('connection_id', 'npm_id', name='uq_npm_hosts_connection_npm_id')
    )
    op.create_index(op.f('ix_npm_hosts_application_id'), 'npm_hosts', ['application_id'], unique=False)
    op.create_index(op.f('ix_npm_hosts_connection_id'), 'npm_hosts', ['connection_id'], unique=False)
    op.create_index(op.f('ix_npm_hosts_organization_id'), 'npm_hosts', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npm_hosts_organization_id'), table_name='npm_hosts')
    op.drop_index(op.f('ix_npm_hosts_connection_id'), table_name='npm_hosts')
    op.drop_index(op.f('ix_npm_hosts_application_id'), table_name='npm_hosts')
    op.drop_table('npm_hosts')
    op.drop_index(op.f('ix_npm_connections_organization_id'), table_name='npm_connections')
    op.drop_table('npm_connections')
    op.drop_index(op.f('ix_applications_organization_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
