"""phase2 vault for bitwarden clients

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 14:03:58.628428
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('kdf_salt', sa.String(length=320), nullable=False),
    sa.Column('kdf_type', sa.Integer(), nullable=False),
    sa.Column('kdf_iterations', sa.Integer(), nullable=False),
    sa.Column('kdf_memory', sa.Integer(), nullable=True),
    sa.Column('kdf_parallelism', sa.Integer(), nullable=True),
    sa.Column('master_password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_key', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.Column('account_keys_v2', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_key_id', sa.String(length=64), nullable=True),
    sa.Column('security_stamp', sa.String(length=64), nullable=False),
    sa.Column('revision_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('kdf_type IN (0, 1)', name=op.f('ck_vault_accounts_kdf_type_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vault_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_vault_accounts')),
    sa.UniqueConstraint('email', name='uq_vault_accounts_email')
    )
    op.create_table('vault_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['vault_accounts.user_id'], name=op.f('fk_vault_devices_user_id_vault_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_devices')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_vault_devices_refresh_token_hash')),
    sa.UniqueConstraint('user_id', 'identifier', name='uq_vault_devices_user_identifier')
    )
    op.create_index(op.f('ix_vault_devices_user_id'), 'vault_devices', ['user_id'], unique=False)
    op.create_table('vault_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('revision_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vault_accounts.user_id'], name=op.f('fk_vault_folders_user_id_vault_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_folders'))
    )
    op.create_index(op.f('ix_vault_folders_user_id'), 'vault_folders', ['user_id'], unique=False)
    op.create_table('vault_ciphers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('type BETWEEN 1 AND 99', name=op.f('ck_vault_ciphers_type_valid')),
    sa.ForeignKeyConstraint(['folder_id'], ['vault_folders.id'], name=op.f('fk_vault_ciphers_folder_id_vault_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['vault_accounts.user_id'], name=op.f('fk_vault_ciphers_user_id_vault_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_ciphers'))
    )
    op.create_index(op.f('ix_vault_ciphers_user_id'), 'vault_ciphers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_ciphers_user_id'), table_name='vault_ciphers')
    op.drop_table('vault_ciphers')
    op.drop_index(op.f('ix_vault_folders_user_id'), table_name='vault_folders')
    op.drop_table('vault_folders')
    op.drop_index(op.f('ix_vault_devices_user_id'), table_name='vault_devices')
    op.drop_table('vault_devices')
    op.drop_table('vault_accounts')
    # ### end Alembic commands ###
