"""phase4 authentik automation

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 16:39:47.381711
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentik_protections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('npm_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('external_host', sa.String(length=2048), nullable=False),
    sa.Column('outpost_pk', sa.String(length=64), nullable=False),
    sa.Column('outpost_name', sa.String(length=255), nullable=True),
    sa.Column('outpost_assigned', sa.Boolean(), nullable=False),
    sa.Column('provider_pk', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('provider_created', sa.Boolean(), nullable=False),
    sa.Column('application_slug', sa.String(length=255), nullable=True),
    sa.Column('application_name', sa.String(length=255), nullable=True),
    sa.Column('application_created', sa.Boolean(), nullable=False),
    sa.Column('access', sa.String(length=80), nullable=False),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cleanup_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['npm_connections.id'], name=op.f('fk_authentik_protections_connection_id_npm_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_authentik_protections_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authentik_protections')),
    sa.UniqueConstraint('connection_id', 'npm_id', name='uq_authentik_protections_connection_npm_id')
    )
    op.create_index(op.f('ix_authentik_protections_connection_id'), 'authentik_protections', ['connection_id'], unique=False)
    op.create_index(op.f('ix_authentik_protections_organization_id'), 'authentik_protections', ['organization_id'], unique=False)
    op.add_column('npm_changes', sa.Column('authentik', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('npm_connections', sa.Column('authentik_outpost_pk', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npm_connections', 'authentik_outpost_pk')
    op.drop_column('npm_changes', 'authentik')
    op.drop_index(op.f('ix_authentik_protections_organization_id'), table_name='authentik_protections')
    op.drop_index(op.f('ix_authentik_protections_connection_id'), table_name='authentik_protections')
    op.drop_table('authentik_protections')
    # ### end Alembic commands ###
